// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// ws2812 //
// ------ //

#define ws2812_wrap_target 0
#define ws2812_wrap 3
#define ws2812_pio_version 0

#define ws2812_T1 3
#define ws2812_T2 3
#define ws2812_T3 4

static const uint16_t ws2812_program_instructions[] = {
            //     .wrap_target
    0x6321, //  0: out    x, 1            side 0 [3]
    0x1223, //  1: jmp    !x, 3           side 1 [2]
    0x1200, //  2: jmp    0               side 1 [2]
    0xa242, //  3: nop                    side 0 [2]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ws2812_program = {
    .instructions = ws2812_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = ws2812_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ws2812_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ws2812_wrap_target, offset + ws2812_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

#include "hardware/clocks.h"
// pio is the instance, sm is choosing the state machine, offset is where program is loaded in 5bit address space
// pin is GPIO pin, freq is baud rate, rgbw is true if the strip also has white
static inline void ws2812_program_init(PIO pio, uint sm, uint offset, uint pin, float freq, bool rgbw) {
    pio_gpio_init(pio, pin); // configure pin to be used for GPIO
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true); //sets the pin to be an output
    pio_sm_config c = ws2812_program_get_default_config(offset); //get the default configuration using generated program from PIO
    sm_config_set_sideset_pins(&c, pin); //make it so that the side set writes to the pin we are using
    sm_config_set_out_shift(&c, false, true, rgbw ? 32 : 24); //want it to shift out MSB first
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX); 
    int cycles_per_bit = ws2812_T1 + ws2812_T2 + ws2812_T3; //total number of execution cycles based on T1, T2, and T3
    float div = clock_get_hz(clk_sys) / (freq * cycles_per_bit); //slow down the clock of the state machine to get the right bit rate
    sm_config_set_clkdiv(&c, div); //actually slow it down
    pio_sm_init(pio, sm, offset, &c); //load into state machine and go to start address which is at offset
    pio_sm_set_enabled(pio, sm, true); //make it go
}

#endif

